"""Persistent virtual pointer for the demo stage.

Headless sway only renders a cursor while the seat has a pointer device,
and one-shot injectors (wlrctl) destroy theirs on exit — so the cursor
would never appear in captures. This daemon holds a wlr virtual pointer
open for the whole session and executes movement/click commands from
stdin (one JSON object per line):

    {"op": "move", "x": 700, "y": 400}        logical px
    {"op": "button", "btn": "left", "state": 1}
    {"op": "quit"}

Prints "ready" once the pointer exists. Requires pywayland; the protocol
bindings are generated by session.py into <gen>/proto (argv[1] = gen dir;
argv[2], argv[3] = logical stage width/height for the motion extents).
"""

import json
import sys
import time

sys.path.insert(0, sys.argv[1])
from pywayland.client import Display  # noqa: E402
from proto.wayland import WlSeat  # noqa: E402
from proto.wlr_virtual_pointer_unstable_v1 import (  # noqa: E402
    ZwlrVirtualPointerManagerV1,
)

# Logical stage size; motion_absolute maps x/y against these extents.
EXTENT_W, EXTENT_H = int(sys.argv[2]), int(sys.argv[3])
BTN = {"left": 0x110, "right": 0x111, "middle": 0x112}

state = {}


def on_global(registry, id_, iface, version):
    if iface == "zwlr_virtual_pointer_manager_v1":
        state["mgr"] = registry.bind(id_, ZwlrVirtualPointerManagerV1, 1)
    elif iface == "wl_seat" and "seat" not in state:
        state["seat"] = registry.bind(id_, WlSeat, 1)


def now_ms() -> int:
    return int(time.monotonic() * 1000) & 0xFFFFFFFF


def main() -> int:
    disp = Display()
    disp.connect()
    reg = disp.get_registry()
    reg.dispatcher["global"] = on_global
    disp.roundtrip()
    if "mgr" not in state:
        print("compositor lacks zwlr_virtual_pointer_manager_v1",
              file=sys.stderr)
        return 1
    ptr = state["mgr"].create_virtual_pointer(state.get("seat"))
    disp.roundtrip()
    print("ready", flush=True)
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        cmd = json.loads(line)
        op = cmd["op"]
        if op == "move":
            ptr.motion_absolute(now_ms(), int(cmd["x"]), int(cmd["y"]),
                                EXTENT_W, EXTENT_H)
            ptr.frame()
        elif op == "button":
            ptr.button(now_ms(), BTN[cmd["btn"]], 1 if cmd["state"] else 0)
            ptr.frame()
        elif op == "quit":
            break
        disp.roundtrip()
    disp.disconnect()
    return 0


if __name__ == "__main__":
    sys.exit(main())
